title: Modernist theme1
description: Modernist is a theme for GitHub Pages..
# show_downloads: true
google_analytics:
theme: jekyll-theme-modernist
defaults: 
  scope:
    path: "笔记"
  values:
    note: true